#!/bin/bash

options=(
    style=round
    width=6.0
    hidpi=on
    active_color=0xff499180
    inactive_color=0xa0252c2d
    order=above # helps with maxos shadows drawing over borders
)

borders "${options[@]}"
