#!/bin/bash

options=(
    style=square
    width=8.0
    hidpi=on
    active_color=0xff76946a
    inactive_color=0xff1f1f28
    order=above # helps with maxos shadows drawing over borders
)

borders "${options[@]}"
