#!/bin/bash

options=(
    style=square
    width=10.0
    hidpi=on
    active_color=0xff499180
    inactive_color=0xff171e1f
    order=above # helps with maxos shadows drawing over borders
)

borders "${options[@]}"
