#!/usr/bin/env sh
#YABAI STUFF

HORIZON_PINK='0xffe95678'
HORIZON_GREEN='0xff29d398'
HORIZON_BLUE='0xff59e1e3'
HORIZON_BRIGHT_GREEN='0xff09f7a0'

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# binary space partitioning
yabai -m config layout bsp

# make floating windows always on top
yabai -m config window_topmost on

## Change how yabai looks
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 2

# custom space names
#yabai -m space 1 --label one
#yabai -m space 2 --label two
#yabai -m space 3 --label three
#yabai -m space 4 --label four
#yabai -m space 5 --label five
#yabai -m space 6 --label six
#yabai -m space 9 --label nine

# Disable layout for some apps - as a rule we want these "always on top"
yabai -m rule --add app="^1Password" manage=off sticky=on layer=above
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Bartender" sticky=on layer=above manage=off
# yabai -m rule --add app="^console$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Fantastical$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Messages$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" sticky=on layer=above manage=off
yabai -m rule --add app="^Photo Booth$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^DisplayLink.*$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Things$" sticky=on layer=above manage=off
yabai -m rule --add app="^Stickies$" sticky=on layer=above manage=off
yabai -m rule --add app="^Wally$" sticky=on layer=above manage=off
yabai -m rule --add app="iStat" sticky=on layer=above manage=off

## Some random global settings
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost on

## Window Border
yabai -m config window_border on
yabai -m config active_window_border_color $HORIZON_BRIGHT_GREEN
yabai -m config normal_window_border_color '0x20'
yabai -m config window_border_width 3

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# makes mouse follow the focus
yabai -m config mouse_follows_focus off

# integration with spacebar
# https://github.com/cmacrae/spacebar
yabai -m config external_bar all:32:0

echo "yabai configuration loaded.."

#END
