#!/usr/bin/env sh
#YABAI STUFF

HORIZON_PINK='0xffe95678'
HORIZON_GREEN='0xff29d398'
HORIZON_BLUE='0xff59e1e3'
HORIZON_BRIGHT_GREEN='0xff09f7a0'

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    layout                       bsp            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity               on             \
    window_opacity_duration      0.08           \
    active_window_opacity        1.0            \
    normal_window_opacity        0.94           \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  2              \
    bottom_padding               0              \
    left_padding                 4              \
    right_padding                4              \
    window_gap                   6              \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# binary space partitioning
yabai -m config layout bsp

# make floating windows always on top
yabai -m config window_topmost on

# custom space names
#yabai -m space 1 --label one
#yabai -m space 2 --label two
#yabai -m space 3 --label three
#yabai -m space 4 --label four
#yabai -m space 5 --label five
#yabai -m space 6 --label six
#yabai -m space 9 --label nine

# Disable layout for some apps - as a rule we want these "always on top"
yabai -m rule --add app="^1Password" manage=off sticky=on layer=above
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Bartender" sticky=on layer=above manage=off
# yabai -m rule --add app="^console$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Fantastical$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Messages$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" sticky=on layer=above manage=off
yabai -m rule --add app="^Photo Booth$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^DisplayLink.*$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Things$" sticky=on layer=above manage=off
yabai -m rule --add app="^Stickies$" sticky=on layer=above manage=off
yabai -m rule --add app="^Wally$" sticky=on layer=above manage=off
yabai -m rule --add app="iStat" sticky=on layer=above manage=off

## Some random global settings
# New window spawns to the right if vertical split, or bottom if horizontal split

## Window Border
yabai -m config window_border on
yabai -m config active_window_border_color $HORIZON_BRIGHT_GREEN
yabai -m config normal_window_border_color '0x20'
yabai -m config window_border_width 3

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# integration with spacebar
# https://github.com/cmacrae/spacebar
yabai -m config external_bar all:32:0

echo "yabai configuration loaded.."

#END
