#!/usr/bin/env sh

#spacebar -m config debug_output on

SPACEBAR_COLOUR_BG='0xa01a1c23'

# green theme
SPACEBAR_COLOUR_FG='0xf027d796'
SPACEBAR_COLOUR_HIGHLIGHT='0xff09f7a0'
SPACEBAR_COLOUR_ICON='0xff21bfc2'

# pink theme here
# SPACEBAR_COLOUR_FG='0xf0e9436f'
# SPACEBAR_COLOUR_HIGHLIGHT='0xfff43e5c'
# SPACEBAR_COLOUR_ICON='0xff6c6f93'

spacebar -m config position             top
spacebar -m config height               32
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "Hasklug Nerd Font:Semibold:15.0"
spacebar -m config icon_font            "Hasklug Nerd Font:Regular:18.0"

spacebar -m config background_color     $SPACEBAR_COLOUR_BG
spacebar -m config foreground_color     $SPACEBAR_COLOUR_FG

spacebar -m config title                off

spacebar -m config spaces               on
spacebar -m config spaces_for_all_displays off
spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9 10
spacebar -m config space_icon           
spacebar -m config space_icon_color     $SPACEBAR_COLOUR_HIGHLIGHT
spacebar -m config space_icon_color_secondary $SPACEBAR_COLOUR_ICON
spacebar -m config clock_icon_color     $SPACEBAR_COLOUR_ICON

spacebar -m config clock                on
spacebar -m config clock_format         "%Y-%m-%d %H:%M"
spacebar -m config clock_icon           

spacebar -m config right_shell_icon     
spacebar -m config right_shell_icon_color   $SPACEBAR_COLOUR_ICON
spacebar -m config right_shell_command  "whoami"

spacebar -m config left_shell_icon     ' '
spacebar -m config left_shell_icon_color $SPACEBAR_COLOUR_ICON
spacebar -m config left_shell_command "$HOME/.scripts/timew_now.sh"

spacebar -m config power                off

# need to do this hack to avoid the shell locking up the config
(spacebar -m config left_shell on) &
(spacebar -m config right_shell on) &

